<?php /* Smarty version 2.6.26, created on 2014-11-08 14:19:12
         compiled from tpl_head:25 */

$this->_cache_serials['/home/workspace/flyingpie.nl/cmsms-1.10/tmp/templates_c/%%87^872^872DD409%%tpl_head%3A25.inc'] = '41f2883a53567ca741d03235b68d370a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'sitename', 'tpl_head:25', 2, false),array('function', 'title', 'tpl_head:25', 2, false),array('function', 'metadata', 'tpl_head:25', 20, false),array('function', 'cms_stylesheet', 'tpl_head:25', 21, false),)), $this); ?>
<?php
function _smarty_tplfunc_41f2883a53567ca741d03235b68d370a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('41f2883a53567ca741d03235b68d370a','0');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_41f2883a53567ca741d03235b68d370a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('41f2883a53567ca741d03235b68d370a','1');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_41f2883a53567ca741d03235b68d370a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('41f2883a53567ca741d03235b68d370a','2');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_41f2883a53567ca741d03235b68d370a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('41f2883a53567ca741d03235b68d370a','3');echo smarty_cms_function_cms_stylesheet(array(), $_smarty);
}



?>
