<?php /* Smarty version 2.6.26, created on 2014-11-08 14:19:37
         compiled from tpl_body:24 */

$this->_cache_serials['/home/workspace/flyingpie.nl/cmsms-1.10/tmp/templates_c/%%9F^9F5^9F529885%%tpl_body%3A24.inc'] = '74344f86a8cc827a4c09ce0702a99be0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'menu', 'tpl_body:24', 12, false),array('function', 'title', 'tpl_body:24', 18, false),array('function', 'content', 'tpl_body:24', 19, false),)), $this); ?>
<?php
function _smarty_tplfunc_74344f86a8cc827a4c09ce0702a99be0_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('74344f86a8cc827a4c09ce0702a99be0','0');echo smarty_cms_function_menu(array(), $_smarty);
}


function _smarty_tplfunc_74344f86a8cc827a4c09ce0702a99be0_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('74344f86a8cc827a4c09ce0702a99be0','1');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_74344f86a8cc827a4c09ce0702a99be0_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('74344f86a8cc827a4c09ce0702a99be0','2');echo smarty_cms_function_content(array(), $_smarty);
}



?>
