<?php /* Smarty version 2.6.26, created on 2014-11-08 14:19:37
         compiled from tpl_top:24 */

$this->_cache_serials['/home/workspace/flyingpie.nl/cmsms-1.10/tmp/templates_c/%%BB^BB8^BB846DBE%%tpl_top%3A24.inc'] = 'e7687989e79e982fb7048dd3c1dd9030';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:24', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_e7687989e79e982fb7048dd3c1dd9030_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e7687989e79e982fb7048dd3c1dd9030','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
