<?php /* Smarty version 2.6.26, created on 2014-11-08 14:19:12
         compiled from tpl_top:25 */

$this->_cache_serials['/home/workspace/flyingpie.nl/cmsms-1.10/tmp/templates_c/%%CC^CC8^CC835D28%%tpl_top%3A25.inc'] = 'bc8851080252cd8c61d1fd9d567b7abb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:25', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_bc8851080252cd8c61d1fd9d567b7abb_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bc8851080252cd8c61d1fd9d567b7abb','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
