<?php /* Smarty version 2.6.26, created on 2014-11-08 14:19:12
         compiled from tpl_body:25 */

$this->_cache_serials['/home/workspace/flyingpie.nl/cmsms-1.10/tmp/templates_c/%%E8^E85^E855A813%%tpl_body%3A25.inc'] = 'eef9876d9d084a5877264f09f19df9c8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'menu', 'tpl_body:25', 12, false),array('function', 'content', 'tpl_body:25', 18, false),)), $this); ?>
<?php
function _smarty_tplfunc_eef9876d9d084a5877264f09f19df9c8_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('eef9876d9d084a5877264f09f19df9c8','0');echo smarty_cms_function_menu(array(), $_smarty);
}


function _smarty_tplfunc_eef9876d9d084a5877264f09f19df9c8_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('eef9876d9d084a5877264f09f19df9c8','1');echo smarty_cms_function_content(array(), $_smarty);
}



?>
