<?php /* Smarty version 2.6.26, created on 2014-11-08 14:19:38
         compiled from tpl_head:24 */

$this->_cache_serials['/home/workspace/flyingpie.nl/cmsms-1.10/tmp/templates_c/%%F0^F02^F02AE49F%%tpl_head%3A24.inc'] = '7e5d8e290dbbc807834257545040f4c8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'sitename', 'tpl_head:24', 2, false),array('function', 'title', 'tpl_head:24', 2, false),array('function', 'metadata', 'tpl_head:24', 19, false),array('function', 'cms_stylesheet', 'tpl_head:24', 20, false),)), $this); ?>
<?php
function _smarty_tplfunc_7e5d8e290dbbc807834257545040f4c8_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7e5d8e290dbbc807834257545040f4c8','0');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_7e5d8e290dbbc807834257545040f4c8_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7e5d8e290dbbc807834257545040f4c8','1');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7e5d8e290dbbc807834257545040f4c8_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7e5d8e290dbbc807834257545040f4c8','2');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7e5d8e290dbbc807834257545040f4c8_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7e5d8e290dbbc807834257545040f4c8','3');echo smarty_cms_function_cms_stylesheet(array(), $_smarty);
}



?>
