<?php /* Smarty version 2.6.26, created on 2014-11-08 14:24:00
         compiled from content:content_en */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'global_content', 'content:content_en', 1, false),array('function', 'popup_image', 'content:content_en', 3, false),array('function', 'cms_selflink', 'content:content_en', 25, false),)), $this); ?>
<?php $this->_cache_serials['/home/workspace/flyingpie.nl/cmsms-1.10/tmp/templates_c/58^%%70^707^707A8977%%content%3Acontent_en.inc'] = '31f0965664af3625544e550dd1593a80'; ?><?php if ($this->caching && !$this->_cache_including): echo '{nocache:31f0965664af3625544e550dd1593a80#0}'; endif;$_cache_attrs =& $this->_smarty_cache_attrs('31f0965664af3625544e550dd1593a80','0');echo smarty_cms_function_global_content(array('name' => 'menu_madstats'), $this);if ($this->caching && !$this->_cache_including): echo '{/nocache:31f0965664af3625544e550dd1593a80#0}'; endif;?>

<p>Madstats provides an easy to use webinterface to Source dedicated servers (srcds), mainly Counter-Strike Source. It displays statistics such as rankings and per player details, based on data generated by <a href="http://www.mani-admin-plugin.com">Mani's Admin Plugin</a>.</p>
<p><?php if ($this->caching && !$this->_cache_including): echo '{nocache:31f0965664af3625544e550dd1593a80#1}'; endif;$_cache_attrs =& $this->_smarty_cache_attrs('31f0965664af3625544e550dd1593a80','1');echo cms_user_tag_popup_image(array('src' => "madstats/playerlist.png",'title' => 'Player list','desc' => 'The player list is the home page and shows all players that have joined the server','style' => "float: left;"), $this);if ($this->caching && !$this->_cache_including): echo '{/nocache:31f0965664af3625544e550dd1593a80#1}'; endif;?>
</p>
<p><?php if ($this->caching && !$this->_cache_including): echo '{nocache:31f0965664af3625544e550dd1593a80#2}'; endif;$_cache_attrs =& $this->_smarty_cache_attrs('31f0965664af3625544e550dd1593a80','2');echo cms_user_tag_popup_image(array('src' => "madstats/playerdetails.png",'title' => 'Player details','desc' => "The player details screen features various ingame statistics, but also information from the player's Steam account",'style' => "float: left;"), $this);if ($this->caching && !$this->_cache_including): echo '{/nocache:31f0965664af3625544e550dd1593a80#2}'; endif;?>
</p>
<p><?php if ($this->caching && !$this->_cache_including): echo '{nocache:31f0965664af3625544e550dd1593a80#3}'; endif;$_cache_attrs =& $this->_smarty_cache_attrs('31f0965664af3625544e550dd1593a80','3');echo cms_user_tag_popup_image(array('src' => "madstats/servers.png",'title' => 'Servers','desc' => "An example configuration with 2 servers, which can be selected via the web interface",'style' => "float: left;"), $this);if ($this->caching && !$this->_cache_including): echo '{/nocache:31f0965664af3625544e550dd1593a80#3}'; endif;?>
</p>
<p><?php if ($this->caching && !$this->_cache_including): echo '{nocache:31f0965664af3625544e550dd1593a80#4}'; endif;$_cache_attrs =& $this->_smarty_cache_attrs('31f0965664af3625544e550dd1593a80','4');echo cms_user_tag_popup_image(array('src' => "madstats/serverstatus.png",'title' => 'Server status','desc' => "The current map and a list of online players are shown by the server status screen, which can also be used to change the map",'style' => "float: left;"), $this);if ($this->caching && !$this->_cache_including): echo '{/nocache:31f0965664af3625544e550dd1593a80#4}'; endif;?>
</p>
<p><?php if ($this->caching && !$this->_cache_including): echo '{nocache:31f0965664af3625544e550dd1593a80#5}'; endif;$_cache_attrs =& $this->_smarty_cache_attrs('31f0965664af3625544e550dd1593a80','5');echo cms_user_tag_popup_image(array('src' => "madstats/configuration.png",'title' => 'Configuration','desc' => "The web interface can be used to configure various settings, such as main server settings, bot settings and the message of the day",'style' => "float: left;"), $this);if ($this->caching && !$this->_cache_including): echo '{/nocache:31f0965664af3625544e550dd1593a80#5}'; endif;?>
</p>
<p><?php if ($this->caching && !$this->_cache_including): echo '{nocache:31f0965664af3625544e550dd1593a80#6}'; endif;$_cache_attrs =& $this->_smarty_cache_attrs('31f0965664af3625544e550dd1593a80','6');echo cms_user_tag_popup_image(array('src' => "madstats/rconclient.png",'title' => 'Rcon client','desc' => "A small rcon client is available to do any manual configuration or send messages to connected players.",'style' => "float: left;"), $this);if ($this->caching && !$this->_cache_including): echo '{/nocache:31f0965664af3625544e550dd1593a80#6}'; endif;?>
</p>
<p style="clear: left;">Statistics are visible to the public, so players can check out there rank.</p>
<p style="clear: left;"><strong>Features</strong></p>
<ul>
<li>Player overview with basic statistics such as kills and deaths;</li>
<li>Detailed per-player statistics view with extensive information on the player ranging from kill/death ratio to kills per minute and Steam integration;</li>
<li>Server statistics, which map is running and who is online;</li>
<li>Ajax-based server status panel, showing the status of the server and updates automatically;</li>
<li>List of available configuration options, from basic server configuration to quake sounds;</li>
<li>Graphical editors for different types of configuration options;</li>
<li>Client editting to quickly add or remove clients, modify there permissions and manage groups;</li>
<li>Customizable server status image, for use in e.g. forum signatures;</li>
<li>Rcon integration, change maps, execute configurations or use the rcon console with autocomplete;</li>
<li>Simple templating system to customize the look-and-feel of your site;</li>
<li>API which can be used to retrieve statistics from another application;</li>
<li>Support for internationalization, use Madstats in your own language;</li>
</ul>
<p>Madstats is open source and can be downloaded from the <a href="<?php if ($this->caching && !$this->_cache_including): echo '{nocache:31f0965664af3625544e550dd1593a80#7}'; endif;$_cache_attrs =& $this->_smarty_cache_attrs('31f0965664af3625544e550dd1593a80','7');echo smarty_cms_function_cms_selflink(array('href' => 'madstats-download'), $this);if ($this->caching && !$this->_cache_including): echo '{/nocache:31f0965664af3625544e550dd1593a80#7}'; endif;?>
">downloads</a> page.</p>
<p><strong>Technology</strong></p>
<p>PHP 5</p>