<?php /* Smarty version 2.6.26, created on 2014-11-08 14:23:40
         compiled from content:content_en */

$this->_cache_serials['/home/workspace/flyingpie.nl/cmsms-1.10/tmp/templates_c/59^%%70^707^707A8977%%content%3Acontent_en.inc'] = '9112cb50d6573fe516b825d98c9f7802';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'portfolio_item', 'content:content_en', 5, false),)), $this); ?>
<?php
function _smarty_tplfunc_9112cb50d6573fe516b825d98c9f7802_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9112cb50d6573fe516b825d98c9f7802','0');echo cms_user_tag_portfolio_item(array('link' => 'ludo','title' => 'Ludo','desc' => "Ludo board game, implemented in 3d and runs on Windows and Xbox360",'image' => "ludo/mensergerjeniet.png"), $_smarty);
}


function _smarty_tplfunc_9112cb50d6573fe516b825d98c9f7802_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9112cb50d6573fe516b825d98c9f7802','1');echo cms_user_tag_portfolio_item(array('link' => "txt-doom",'title' => "TxT-Doom",'desc' => "Console interpretation of Doom 95, featuring the original midi music and soundtrack",'image' => "txtdoom/txtdoom.png"), $_smarty);
}


function _smarty_tplfunc_9112cb50d6573fe516b825d98c9f7802_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9112cb50d6573fe516b825d98c9f7802','2');echo cms_user_tag_portfolio_item(array('link' => 'madstats','title' => 'Madstats','desc' => "Game statistics and server management for Source-based games",'image' => "madstats/madstats.png"), $_smarty);
}


function _smarty_tplfunc_9112cb50d6573fe516b825d98c9f7802_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9112cb50d6573fe516b825d98c9f7802','3');echo cms_user_tag_portfolio_item(array('link' => "the-winning-sudoku",'title' => 'The Winning Sudoku','desc' => "Sudoku app for Android, featuring a board designer to create custom multiple board layouts",'image' => "sudoku/sudoku.png"), $_smarty);
}


function _smarty_tplfunc_9112cb50d6573fe516b825d98c9f7802_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9112cb50d6573fe516b825d98c9f7802','4');echo cms_user_tag_portfolio_item(array('link' => 'steamdroid','title' => 'Steam Droid','desc' => "Steam friends app for Android, enabling steam chat from mobile devices",'image' => "steamdroid/mainmenu.png"), $_smarty);
}


function _smarty_tplfunc_9112cb50d6573fe516b825d98c9f7802_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9112cb50d6573fe516b825d98c9f7802','5');echo cms_user_tag_portfolio_item(array('link' => "the-winning-scrumboard",'title' => 'The Winning Scrumboard','desc' => "Digital scrumboard for collaborative project management, specifically built for use with touch devices",'image' => "scrumboard/sprint.png"), $_smarty);
}


function _smarty_tplfunc_9112cb50d6573fe516b825d98c9f7802_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9112cb50d6573fe516b825d98c9f7802','6');echo cms_user_tag_portfolio_item(array('link' => "server-config-generator",'title' => 'Server config generator','desc' => "Configuration generator for Source-based servers, making it easier to create a custom config file",'image' => "serverconfiggenerator/serverconfiggenerator.png"), $_smarty);
}



?>
