<?php /* Smarty version 2.6.26, created on 2014-11-11 20:02:02
         compiled from content:content_en */

$this->_cache_serials['/home/workspace/flyingpie.nl/cmsms-1.10/tmp/templates_c/62^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'b12cb776f7880fba0504c96947a8a989';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'popup_image', 'content:content_en', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b12cb776f7880fba0504c96947a8a989_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b12cb776f7880fba0504c96947a8a989','0');echo cms_user_tag_popup_image(array('src' => "sudoku/menuscreen.png",'title' => 'Menu screen','desc' => "Menu screen, with the choice to create a new game or design a custom board",'style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_b12cb776f7880fba0504c96947a8a989_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b12cb776f7880fba0504c96947a8a989','1');echo cms_user_tag_popup_image(array('src' => "sudoku/newgame.png",'title' => 'New game','desc' => "A new game can have one out of five difficulties and 3 different board sizes, optionally combined into a single game",'style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_b12cb776f7880fba0504c96947a8a989_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b12cb776f7880fba0504c96947a8a989','2');echo cms_user_tag_popup_image(array('src' => "sudoku/standardgame.png",'title' => 'Standard game','desc' => 'Standard 9 by 9 sudoku board','style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_b12cb776f7880fba0504c96947a8a989_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b12cb776f7880fba0504c96947a8a989','3');echo cms_user_tag_popup_image(array('src' => "sudoku/doubleboard.png",'title' => 'Double board','desc' => "Two 9 by 9 boards, joined into a single game",'style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_b12cb776f7880fba0504c96947a8a989_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b12cb776f7880fba0504c96947a8a989','4');echo cms_user_tag_popup_image(array('src' => "sudoku/designer.png",'title' => 'Board designer','desc' => "Board designer, ability to create a custom game with multiple boards of varying sizes",'style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_b12cb776f7880fba0504c96947a8a989_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b12cb776f7880fba0504c96947a8a989','5');echo cms_user_tag_popup_image(array('src' => "sudoku/customboard.png",'title' => 'Custom board','desc' => "Custom board from designer, automatically filled by the engine",'style' => "float: left;"), $_smarty);
}



?>
