<?php /* Smarty version 2.6.26, created on 2014-11-09 02:38:15
         compiled from content:content_en */

$this->_cache_serials['/home/workspace/flyingpie.nl/cmsms-1.10/tmp/templates_c/64^%%70^707^707A8977%%content%3Acontent_en.inc'] = '246ff8bc2ad8c1c48853d6500153680c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'global_content', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_246ff8bc2ad8c1c48853d6500153680c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('246ff8bc2ad8c1c48853d6500153680c','0');echo smarty_cms_function_global_content(array('name' => 'menu_madstats'), $_smarty);
}



?>
