<?php /* Smarty version 2.6.26, created on 2014-11-11 20:03:02
         compiled from content:content_en */

$this->_cache_serials['/home/workspace/flyingpie.nl/cmsms-1.10/tmp/templates_c/65^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'a54decc4a584135b7d3e52d08003da40';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'global_content', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_a54decc4a584135b7d3e52d08003da40_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a54decc4a584135b7d3e52d08003da40','0');echo smarty_cms_function_global_content(array('name' => 'menu_madstats_documentation'), $_smarty);
}



?>
