<?php /* Smarty version 2.6.26, created on 2014-11-08 14:24:05
         compiled from content:content_en */

$this->_cache_serials['/home/workspace/flyingpie.nl/cmsms-1.10/tmp/templates_c/66^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'cfe8b50db44c8023f8e7b4e34a9a6f32';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'popup_image', 'content:content_en', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_cfe8b50db44c8023f8e7b4e34a9a6f32_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cfe8b50db44c8023f8e7b4e34a9a6f32','0');echo cms_user_tag_popup_image(array('src' => "steamdroid/mainmenu.png",'title' => 'Main menu','desc' => 'The main menu where a connection to the Steam Droid server can be established','style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_cfe8b50db44c8023f8e7b4e34a9a6f32_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cfe8b50db44c8023f8e7b4e34a9a6f32','1');echo cms_user_tag_popup_image(array('src' => "steamdroid/friendslist.png",'title' => 'Friends list','desc' => "Friends list, with an overview of all friends and there state",'style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_cfe8b50db44c8023f8e7b4e34a9a6f32_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cfe8b50db44c8023f8e7b4e34a9a6f32','2');echo cms_user_tag_popup_image(array('src' => "steamdroid/chat.png",'title' => 'Chat','desc' => 'Chats get displayed in a scrolling list','style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_cfe8b50db44c8023f8e7b4e34a9a6f32_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cfe8b50db44c8023f8e7b4e34a9a6f32','3');echo cms_user_tag_popup_image(array('src' => "steamdroid/notification.png",'title' => 'Notifications','desc' => "When a chat message is received while that specific chat is not open, alerts can be made via the notifications bar, sound and vibrate",'style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_cfe8b50db44c8023f8e7b4e34a9a6f32_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cfe8b50db44c8023f8e7b4e34a9a6f32','4');echo cms_user_tag_popup_image(array('src' => "steamdroid/settings.png",'title' => 'Settings','desc' => "Credentials, SteamDroid server information and alerts can be changed via the settings menu",'style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_cfe8b50db44c8023f8e7b4e34a9a6f32_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cfe8b50db44c8023f8e7b4e34a9a6f32','5');echo cms_user_tag_popup_image(array('src' => "steamdroid/changestate.png",'title' => 'Change state','desc' => "Change the current state to online, away, busy, snooze or offline",'style' => "float: left;"), $_smarty);
}



?>
