<?php /* Smarty version 2.6.26, created on 2014-11-10 05:01:14
         compiled from content:content_en */

$this->_cache_serials['/home/workspace/flyingpie.nl/cmsms-1.10/tmp/templates_c/72^%%70^707^707A8977%%content%3Acontent_en.inc'] = '0c80dad0e4083d43da497f34afd1a08d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'global_content', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_0c80dad0e4083d43da497f34afd1a08d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0c80dad0e4083d43da497f34afd1a08d','0');echo smarty_cms_function_global_content(array('name' => 'menu_madstats_documentation'), $_smarty);
}



?>
