<?php /* Smarty version 2.6.26, created on 2014-11-08 14:24:12
         compiled from content:content_en */

$this->_cache_serials['/home/workspace/flyingpie.nl/cmsms-1.10/tmp/templates_c/74^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'bc642b683fe91206fd83955d29ed4a7f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'popup_image', 'content:content_en', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_bc642b683fe91206fd83955d29ed4a7f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bc642b683fe91206fd83955d29ed4a7f','0');echo cms_user_tag_popup_image(array('src' => "scrumboard/sprint.png",'title' => 'Sprint view','desc' => 'View of a single sprint with its backlog items','style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_bc642b683fe91206fd83955d29ed4a7f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bc642b683fe91206fd83955d29ed4a7f','1');echo cms_user_tag_popup_image(array('src' => "scrumboard/details.png",'title' => 'Detail view','desc' => "Sprint backlog item detail view, can edit the sbi's properties",'style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_bc642b683fe91206fd83955d29ed4a7f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bc642b683fe91206fd83955d29ed4a7f','2');echo cms_user_tag_popup_image(array('src' => "scrumboard/history.png",'title' => 'Backlog item history','desc' => "History of a sprint backlog item, indicates how long each status took",'style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_bc642b683fe91206fd83955d29ed4a7f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bc642b683fe91206fd83955d29ed4a7f','3');echo cms_user_tag_popup_image(array('src' => "scrumboard/burndown.png",'title' => 'Burn down chart','desc' => "Burn down chart of the current sprint, on the right side of the sprint itself",'style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_bc642b683fe91206fd83955d29ed4a7f_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bc642b683fe91206fd83955d29ed4a7f','4');echo cms_user_tag_popup_image(array('src' => "scrumboard/filter.png",'title' => 'Sprint backlog item filter','desc' => 'Filtering makes a specific selection of backlog items within the sprint','style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_bc642b683fe91206fd83955d29ed4a7f_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bc642b683fe91206fd83955d29ed4a7f','5');echo cms_user_tag_popup_image(array('src' => "scrumboard/zoom.png",'title' => 'Sprint zoom','desc' => "Zooms out the scrumboard for an overview when the backlog items won't fit the screen",'style' => "float: left;"), $_smarty);
}



?>
