<?php /* Smarty version 2.6.26, created on 2014-11-08 14:19:38
         compiled from content:content_en */

$this->_cache_serials['/home/workspace/flyingpie.nl/cmsms-1.10/tmp/templates_c/75^%%70^707^707A8977%%content%3Acontent_en.inc'] = '1fccc684433e9f0271d9e354b30aad7a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'popup_image', 'content:content_en', 7, false),array('function', 'DownCnt', 'content:content_en', 16, false),)), $this); ?>
<?php
function _smarty_tplfunc_1fccc684433e9f0271d9e354b30aad7a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1fccc684433e9f0271d9e354b30aad7a','0');echo cms_user_tag_popup_image(array('src' => "slendermod/house.png",'title' => 'House','style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_1fccc684433e9f0271d9e354b30aad7a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1fccc684433e9f0271d9e354b30aad7a','1');echo cms_user_tag_popup_image(array('src' => "slendermod/station.png",'title' => 'Station','style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_1fccc684433e9f0271d9e354b30aad7a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1fccc684433e9f0271d9e354b30aad7a','2');echo cms_user_tag_popup_image(array('src' => "slendermod/playground.png",'title' => 'Playground','style' => "float: left;"), $_smarty);
}


function _smarty_tplfunc_1fccc684433e9f0271d9e354b30aad7a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1fccc684433e9f0271d9e354b30aad7a','3');echo $_smarty->_plugins['function']['DownCnt'][0][0]->function_plugin(array('name' => "slendermod_v1.0_cdn",'link' => 'http://www.mediafire.com/?3cqbp9l83zczryy'), $_smarty);
}


function _smarty_tplfunc_1fccc684433e9f0271d9e354b30aad7a_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1fccc684433e9f0271d9e354b30aad7a','4');echo $_smarty->_plugins['function']['DownCnt'][0][0]->function_plugin(array('name' => "slendermod_v1.0_mac_cdn",'link' => 'http://www.mediafire.com/?6ypmml12lh47wbc'), $_smarty);
}


function _smarty_tplfunc_1fccc684433e9f0271d9e354b30aad7a_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1fccc684433e9f0271d9e354b30aad7a','5');echo $_smarty->_plugins['function']['DownCnt'][0][0]->function_plugin(array('name' => "slendermod_v1.0",'link' => "uploads/files/slendermod/SlenderMod_v1.0.zip"), $_smarty);
}


function _smarty_tplfunc_1fccc684433e9f0271d9e354b30aad7a_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1fccc684433e9f0271d9e354b30aad7a','6');echo $_smarty->_plugins['function']['DownCnt'][0][0]->function_plugin(array('name' => "slendermod_v1.0_mac",'link' => "uploads/files/slendermod/SlenderMod_v1.0_Mac.zip"), $_smarty);
}



?>
