<?php /* Smarty version 2.6.26, created on 2014-11-17 22:01:27
         compiled from module_file_tpl:MicroTiny%3Bmicrotinyconfig.tpl */

$this->_cache_serials['/home/workspace/flyingpie.nl/cmsms-1.10/tmp/templates_c/MicroTiny^%%A4^A4D^A4D98377%%module_file_tpl%3AMicroTiny%3Bmicrotinyconfig.tpl.inc'] = 'b63a2d19818764536b2f279ca89bc7bb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_stylesheet', 'module_file_tpl:MicroTiny;microtinyconfig.tpl', 8, false),)), $this); ?>
<?php
function _smarty_tplfunc_b63a2d19818764536b2f279ca89bc7bb_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b63a2d19818764536b2f279ca89bc7bb','0');echo smarty_cms_function_cms_stylesheet(array('templateid' => $_smarty->_tpl_vars['templateid'],'nolinks' => 1,'adjustforeditor' => 1), $_smarty);
}


function _smarty_tplfunc_b63a2d19818764536b2f279ca89bc7bb_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b63a2d19818764536b2f279ca89bc7bb','1');echo smarty_cms_function_cms_stylesheet(array('templateid' => $_smarty->_tpl_vars['templateid'],'nolinks' => 1), $_smarty);
}



?>
